name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull Changes to Sibast on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Sibast/
            git pull origin main

      - name: Build Sibast Web Build Files
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Sibast/
            npm run build

      - name: Set Public_html Folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Sibast/
            cp -rf public/* ../../public_html/Sibast/
            cd ../../public_html/Sibast/
            rm -rf assets/ build/
            mv -f public/{.[!.]*,*} .
            rm -rf public/
            cp -f index.prod.php index.php
