name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Clone the repository
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       rm -rf Sibast
      #       git clone https://github.com/HanslettTheDev/Sibast.git -b main
      
      - name: Pull Changes to Sibast on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Sibast/
            git pull origin main

      - name: Build VueJS frontend Files
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            bash -l -c 'cd Sibast && npm install && npm run build'

      - name: Moves web files to web directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd Sibast/
            cp -rf public ../public_html/Sibast/public/
            cd ../public_html/Sibast/public
            rm -rf assets/ build/
            mv -f public/* . && mv -f public/.htaccess .
            rm -rf public/
            cp -f index.prod.php index.php
            ls -al
